# This is a Docker Compose file for a microservices architecture
# It includes services for NATS, MongoDB, MinIO, and various application services
# its only for development purposes

services:
  nats-ui:
    depends_on:
      - nats
    image: ghcr.io/nats-nui/nui
    ports:
      - "31311:31311" # Monitoring
    networks:
      - default

  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # Monitoring
    command: ["-js"] # Enable JetStream
    networks:
      - default

  gateway:
    depends_on:
      - nats
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile

    ports:
      - "8081:8080"
    networks:
      - default

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - default

  user-service:
    depends_on:
      - nats
      - mongo
    build:
      context: .
      dockerfile: cmd/user-service/Dockerfile

    ports:
      - "8082:8080"
    networks:
      - default

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: access-key-id
      MINIO_ROOT_PASSWORD: secret-access-key
    networks:
      - default
    command: server /data --console-address ":9001"

  angebot-service:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: cmd/angebot-service/Dockerfile
    ports:
      - "8084:8080"
    networks:
      - default

  media-service:
    depends_on:
      - nats
      - minio
    build:
      context: .
      dockerfile: cmd/media-service/Dockerfile

    ports:
      - "8083:8080"
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./cmd/frontend/static:/app/cmd/frontend/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: cmd/frontend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
