# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"  # was 1.23

      - name: Test
        run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run

  sonar:
    runs-on: ubuntu-latest
    container:
      image: sonarsource/sonar-scanner-cli:4
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Scan container
        run: |
          sonar-scanner -Dsonar.projectKey=kmsbackend -Dsonar.sources=. -Dsonar.host.url=https://scm.thm.de/sonar -Dsonar.login=${{ secrets.SCQ }}
